import logging
from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional
from app.services.rag_service import RAGService
from app.services.history_service import HistoryService

logger = logging.getLogger("app.routes.chat")
router = APIRouter(prefix="/api/chat", tags=["Chat"])

class ChatRequest(BaseModel):
    sessionId: str = Field(..., description="Unique identifier for the user chat session")
    message: str = Field(..., description="The query text sent by the user")

    class Config:
        json_schema_extra = {
            "example": {
                "sessionId": "demo-session-123",
                "message": "How can I reset my password?"
            }
        }

class SourceMetadata(BaseModel):
    title: str
    text: str
    similarity: float

class ChatResponse(BaseModel):
    reply: str = Field(..., description="The answer generated by the grounded assistant")
    tokensUsed: int = Field(..., description="Total tokens used in prompt and response")
    retrievedChunks: int = Field(..., description="Number of source chunks retrieved")
    sources: List[SourceMetadata] = Field(default=[], description="List of source chunks used for grounding")
    mocked: bool = Field(default=False, description="Flag indicating if the assistant ran in mockup fallback mode")
    error: Optional[str] = Field(default=None, description="Error details, if any occurred during LLM generation")

@router.post("", response_model=ChatResponse, status_code=status.HTTP_200_OK)
def process_chat_message(payload: ChatRequest):
    """
    Receives user message and session identifier, performs similarity search,
    constructs the context-grounded prompt, triggers LLM evaluation, and returns the result.
    """
    if not payload.message.strip():
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Message field cannot be blank."
        )
    if not payload.sessionId.strip():
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="SessionId field cannot be blank."
        )

    try:
        result = RAGService.query(payload.sessionId, payload.message)
        return ChatResponse(
            reply=result["reply"],
            tokensUsed=result["tokensUsed"],
            retrievedChunks=result["retrievedChunks"],
            sources=result.get("sources", []),
            mocked=result.get("mocked", False),
            error=result.get("error")
        )
    except Exception as e:
        logger.error(f"Failed to process chat message for session {payload.sessionId}: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while formulating the assistant response: {str(e)}"
        )

@router.delete("/session/{session_id}", status_code=status.HTTP_200_OK)
def clear_chat_session(session_id: str):
    """
    Clears the cached message history for a given session.
    """
    if not session_id.strip():
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Session ID cannot be blank."
        )
    try:
        HistoryService.clear_history(session_id)
        return {"status": "success", "message": f"History cleared for session '{session_id}'"}
    except Exception as e:
        logger.error(f"Error resetting session {session_id}: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Unable to clear history: {str(e)}"
        )
